//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPushService")]
    public interface IPushService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushService/Register", ReplyAction="http://tempuri.org/IPushService/RegisterResponse")]
        void Register(string strURI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushService/Unregister", ReplyAction="http://tempuri.org/IPushService/UnregisterResponse")]
        void Unregister(string strURI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushService/SendToastNotification", ReplyAction="http://tempuri.org/IPushService/SendToastNotificationResponse")]
        void SendToastNotification(string strTitle, string strSubtitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushService/SendTileNotification", ReplyAction="http://tempuri.org/IPushService/SendTileNotificationResponse")]
        void SendTileNotification(int nCount, string strTitle, string strBackground);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushService/SendRawNotification", ReplyAction="http://tempuri.org/IPushService/SendRawNotificationResponse")]
        void SendRawNotification(string strMessage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPushServiceChannel : PushClient.ServiceReference1.IPushService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PushServiceClient : System.ServiceModel.ClientBase<PushClient.ServiceReference1.IPushService>, PushClient.ServiceReference1.IPushService {
        
        public PushServiceClient() {
        }
        
        public PushServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PushServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PushServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PushServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Register(string strURI) {
            base.Channel.Register(strURI);
        }
        
        public void Unregister(string strURI) {
            base.Channel.Unregister(strURI);
        }
        
        public void SendToastNotification(string strTitle, string strSubtitle) {
            base.Channel.SendToastNotification(strTitle, strSubtitle);
        }
        
        public void SendTileNotification(int nCount, string strTitle, string strBackground) {
            base.Channel.SendTileNotification(nCount, strTitle, strBackground);
        }
        
        public void SendRawNotification(string strMessage) {
            base.Channel.SendRawNotification(strMessage);
        }
    }
}
